/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ikjames647
 */
public class LunchMenu extends javax.swing.JFrame {

    /**
     * Creates new form LunchMenu
     */
    public LunchMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DrinkPics = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Lunch Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 0, 180, 90);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 0, 51));
        jLabel4.setText("Drinks");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 130, 110, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 0, 51));
        jLabel3.setText("Entrees");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 130, 160, 50);

        DrinkPics.setModel(loadImages2());
        getContentPane().add(DrinkPics);
        DrinkPics.setBounds(470, 200, 280, 150);

        jComboBox1.setModel(loadImages());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(80, 200, 300, 150);

        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Need Waiter?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 90, 170, 30);

        jButton3.setForeground(new java.awt.Color(204, 0, 51));
        jButton3.setText("Back");
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 30, 150, 40);

        jButton2.setForeground(new java.awt.Color(204, 0, 51));
        jButton2.setText("Done");
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 30, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ikjames647\\Downloads\\simple_green-HD[1].jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1958, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
private DefaultComboBoxModel<Icon> loadImages()
    {
    DefaultComboBoxModel<Icon> d = new DefaultComboBoxModel<Icon>();
    //Entree1
//d.addElement(new ImageIcon("C:\\Users\\drcouncil\\Documents\\NetBeansProjects\\FoodDude\\src\\entree1.jpg"));    
//Entree2
    d.addElement(new ImageIcon("C:\\Users\\ikjames647\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\220.png"));
    d.addElement(new ImageIcon("C:\\Users\\ikjames647\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images.jpg"));
      return d;
}
private DefaultComboBoxModel<Icon> loadImages2()
    {
    DefaultComboBoxModel<Icon> d = new DefaultComboBoxModel<Icon>();
   
    d.addElement(new ImageIcon("C:\\Users\\ikjames647\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\images_1.jpg"));
      return d;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LunchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LunchMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DrinkPics;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
